### ISSUE TITLE
Discovery issue with iZone

### ISSUE THREAD

**Issue by mikenye** [Swamp-Ig/pizone#5]
Hi,

Thanks for spending your time making this package.

I'm having some issues trying to get my iZone air-conditioner added to home assistant (v0.114.0). It works just fine with the iZone app on my phone.

When I try to add an iZone integration, it eventually times out and I get "No iZone devices found on the network". When I look at the Home Assistant log, I see the following:

```
2020-08-13 12:58:33 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 1019, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 355, in datagram_received
    self._process_datagram(data, addr)
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 372, in _process_datagram
    self._discovery_recieved(data)
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 377, in _discovery_recieved
    or not message[3] in ('iZone', 'iZoneV2')):
IndexError: list index out of range
2020-08-13 12:58:33 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 1019, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 355, in datagram_received
    self._process_datagram(data, addr)
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 372, in _process_datagram
    self._discovery_recieved(data)
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 377, in _discovery_recieved
    or not message[3] in ('iZone', 'iZoneV2')):
IndexError: list index out of range
```

I've tried to manually go through the discovery process in the python shell using the pizone module in order to assist troubleshooting, however I can't figure out how to do this (I'll keep trying).

Any assistance you can provide would be greatly appreciated.

Kind regards,
Mike Nye

**Comment by mikenye** [comment]
Going through the protocol PDF and your code, I was able to use `socat` to issue the discovery packet and get a response. I'm not sure if this helps you, but here's what I get:

```
$ echo "IASD" | socat - UDP-DATAGRAM:255.255.255.255:12107,broadcast
ASPort_12107,Mac_000000103,IP_192.168.69.9
```

**Comment by mikenye** [comment]
Continuing through the PDF...:

```
$ curl http://192.168.69.9:/SystemSettings
```
```json
{
        "AirStreamDeviceUId":   "000000103",
        "DeviceType":   "ASH",
        "SysOn":        "off",
        "SysMode":      "heat",
        "SysFan":       "low",
        "SleepTimer":   0,
        "UnitType":     "Unknown",
        "Supply":       "0.0",
        "Setpoint":     "22.0",
        "Temp": "0.0",
        "RAS":  "master",
        "CtrlZone":     13,
        "Tag1": "",
        "Tag2": "",
        "Warnings":     "filter",
        "ACError":      "",
        "Id":   0,
        "EcoLock":      "true",
        "EcoMax":       "26.0",
        "EcoMin":       "22.0",
        "NoOfConst":    1,
        "NoOfZones":    7,
        "SysType":      "310",
        "AirflowLock":  "off",
        "UnitLocked":   "false"
}
```

**Comment by mikenye** [comment]
If it helps:

```python
import socket

x = socket.socket(
    family=socket.AF_INET,
    type=socket.SOCK_DGRAM,
    proto=socket.IPPROTO_UDP
    )

x.setsockopt(
    socket.SOL_SOCKET,
    socket.SO_BROADCAST, 1
    )

x.sendto(
    b"IASD",
    ('<broadcast>', 12107)
    )

x.recvmsg(1024)
```

returns:

```python
(b'ASPort_12107,Mac_000000103,IP_192.168.69.9', [], 0, ('192.168.69.9', 12107))
```

**Comment by Swamp-Ig** [comment]
That's interesting, it doesn't actually have the fourth record field in it
at all.

I can probably change the discovery code to manage this better, but really
the izone unit should be reporting that there's an izone unit present. You
sure it's connecting to the bridge?

**Comment by mikenye** [comment]
Hi Penny,

Thanks for getting back to me.

> it doesn't actually have the fourth record field in it at all.

What fourth record field are you referring to? The CB response to the discovery datagram? Looking at the PDF there only appears to be three fields?

```
CB responds: “ASPort_PortNo,CB_ID,CB_IP”
```

I'm fairly certain that it's talking to the bridge... I mean I can query the zones/schedules according to the endpoints in the PDF using `curl` and control the system with POSTs:

eg, turning the system on and off:

``` 
# curl http://192.168.69.9/SystemSettings
{
        "AirStreamDeviceUId":   "000000103",
        "DeviceType":   "ASH",
        "SysOn":        "off",
        "SysMode":      "heat",
        "SysFan":       "low",
        "SleepTimer":   0,
        "UnitType":     "Unknown",
        "Supply":       "0.0",
        "Setpoint":     "22.0",
        "Temp": "0.0",
        "RAS":  "master",
        "CtrlZone":     13,
        "Tag1": "",
        "Tag2": "",
        "Warnings":     "filter",
        "ACError":      "",
        "Id":   0,
        "EcoLock":      "true",
        "EcoMax":       "26.0",
        "EcoMin":       "22.0",
        "NoOfConst":    1,
        "NoOfZones":    7,
        "SysType":      "310",
        "AirflowLock":  "off",
        "UnitLocked":   "false"
}

# curl -v -H "Content-Type: application/json" -d '{"SystemON":"on"}' -X POST http://192.168.69.9/SystemON
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.69.9:80...
* Connected to 192.168.69.9 (192.168.69.9) port 80 (#0)
> POST /SystemON HTTP/1.1
> Host: 192.168.69.9
> User-Agent: curl/7.69.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 17
>
* upload completely sent off: 17 out of 17 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: close
< Content-Type: application/json
< Cache-Control: no-cache
<
* Closing connection 0

# curl http://192.168.69.9/SystemSettings
{
        "AirStreamDeviceUId":   "000000103",
        "DeviceType":   "ASH",
        "SysOn":        "on",
        "SysMode":      "heat",
        "SysFan":       "low",
        "SleepTimer":   0,
        "UnitType":     "Unknown",
        "Supply":       "0.0",
        "Setpoint":     "22.0",
        "Temp": "0.0",
        "RAS":  "master",
        "CtrlZone":     13,
        "Tag1": "",
        "Tag2": "",
        "Warnings":     "filter",
        "ACError":      "",
        "Id":   0,
        "EcoLock":      "true",
        "EcoMax":       "26.0",
        "EcoMin":       "22.0",
        "NoOfConst":    1,
        "NoOfZones":    7,
        "SysType":      "310",
        "AirflowLock":  "off",
        "UnitLocked":   "false"
}

# curl -v -H "Content-Type: application/json" -d '{"SystemON":"off"}' -X POST http://192.168.69.9/SystemON
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.69.9:80...
* Connected to 192.168.69.9 (192.168.69.9) port 80 (#0)
> POST /SystemON HTTP/1.1
> Host: 192.168.69.9
> User-Agent: curl/7.69.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 18
>
* upload completely sent off: 18 out of 18 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: close
< Content-Type: application/json
< Cache-Control: no-cache
<
* Closing connection 0

# curl http://192.168.69.9/SystemSettings
{
        "AirStreamDeviceUId":   "000000103",
        "DeviceType":   "ASH",
        "SysOn":        "off",
        "SysMode":      "heat",
        "SysFan":       "low",
        "SleepTimer":   0,
        "UnitType":     "Unknown",
        "Supply":       "0.0",
        "Setpoint":     "22.0",
        "Temp": "0.0",
        "RAS":  "master",
        "CtrlZone":     13,
        "Tag1": "",
        "Tag2": "",
        "Warnings":     "filter",
        "ACError":      "",
        "Id":   0,
        "EcoLock":      "true",
        "EcoMax":       "26.0",
        "EcoMin":       "22.0",
        "NoOfConst":    1,
        "NoOfZones":    7,
        "SysType":      "310",
        "AirflowLock":  "off",
        "UnitLocked":   "false"
}
```

Please let me know what I can do to help troubleshoot, thanks! :-)

-Mike

**Comment by perkins1724** [comment]
> That's interesting, it doesn't actually have the fourth record field in it at all.

+1 to this issue. My unit only returns the three fields from the pdf:
`CB responds: “ASPort_PortNo,CB_ID,CB_IP”`

Manually adding the 4th field with something like this around line 377 of discovery.py gets past the problem:
`if len(message) < 4: message.append("iZone")`

**Comment by mikenye** [comment]
@perkins1724 I haven't added a readme yet, and I'm still working on it, however have started this: https://github.com/mikenye/pyizone.

May be useful to you.

**Comment by Swamp-Ig** [comment]
Ahh, I can see the issue. Will have a go at fixing it. Can someone please test it with their system? Mine does the 4 field discovery message.

**Comment by Swamp-Ig** [comment]
OK I think I have fixed it. If someone wants to test it that would be great. You'll need to replace the existing discovery.py with the new one [here](https://github.com/Swamp-Ig/pizone/blob/master/pizone/discovery.py).

Once this is tested I'll release it.

**Comment by mikenye** [comment]
Hi @Swamp-Ig, sorry for the delay. I've tested the new discovery.py, and unfortunately it still seems to have an issue.

```
2020-10-21 16:54:12 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 1019, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 355, in datagram_received
    self._process_datagram(data, addr)
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 372, in _process_datagram
    self._discovery_recieved(data)
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 377, in _discovery_recieved
    or (len(message) >= 4 and not message[3] in ('iZone', 'iZoneV2'))):
IndexError: list index out of range
```

```
# sha256sum /usr/local/lib/python3.8/site-packages/pizone/discovery.py
b59bbd5a1f94ecc7b216e3f3b296e7411e00ed682db5a421fa5a3d1a6f52dc36  /usr/local/lib/python3.8/site-packages/pizone/discovery.py
```

**Comment by perkins1724** [comment]
Hi @Swamp-Ig : Works for me, thanks!
```
2020-10-21 21:51:42 DEBUG (MainThread) [pizone.discovery] Sending discovery message to addr 172.30.33.255
2020-10-21 21:51:42 DEBUG (MainThread) [pizone.discovery] Datagram Recieved b'ASPort_12107,Mac_000014489,IP_192.168.201.72'
2020-10-21 21:51:42 INFO (MainThread) [pizone.discovery] New controller found: id=000014489 ip=192.168.201.72
2020-10-21 21:51:42 DEBUG (MainThread) [homeassistant.components.izone.config_flow] Controllers {'000014489': <pizone.controller.Controller object at 0x6b009400>}
2020-10-21 21:51:42 INFO (MainThread) [homeassistant.setup] Setting up izone
2020-10-21 21:51:42 INFO (MainThread) [homeassistant.setup] Setup of domain izone took 0.0 seconds
2020-10-21 21:51:42 INFO (MainThread) [homeassistant.components.climate] Setting up climate.izone
2020-10-21 21:51:42 INFO (MainThread) [homeassistant.components.izone.climate] Controller UID=000014489 discovered
```

Hi @mikenye, did you restart the docker container after making the changes? I found that things continued to fail after changing the file (and seeing changes to the logging reflecting the correct changes) until I restarted the container. 

```
# sha256sum /usr/local/lib/python3.8/site-packages/pizone/discovery.py
b59bbd5a1f94ecc7b216e3f3b296e7411e00ed682db5a421fa5a3d1a6f52dc36  /usr/local/lib/python3.8/site-packages/pizone/discovery.py
```

**Comment by mikenye** [comment]
perkins1724 no I didn't, will try that. Thanks.

**Comment by mikenye** [comment]
Hi @Swamp-Ig,

I'm sorry, I'm still having problems.

I performed the following inside the container:

```
cd /usr/local/lib/python3.8/site-packages/pizone/
rm discovery.py
curl -O https://raw.githubusercontent.com/Swamp-Ig/pizone/master/pizone/discovery.py
chmod a+x discovery.py
```

Then restarted the container.

```
2020-11-07 13:11:45 ERROR (MainThread) [pizone.discovery] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 393, in initialize_controller
    await controller._initialize()  # pylint: disable=protected-access  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/pizone/controller.py", line 95, in _initialize
    str(self._system_settings['FanAuto'])]
KeyError: 'FanAuto'
2020-11-07 13:11:45 ERROR (MainThread) [pizone.discovery] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 393, in initialize_controller
    await controller._initialize()  # pylint: disable=protected-access  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/pizone/controller.py", line 95, in _initialize
    str(self._system_settings['FanAuto'])]
KeyError: 'FanAuto'
```

**Comment by mikenye** [comment]
I don't know if it helps, but I can control my aircon with this module I put together: <https://github.com/mikenye/pyizone>

It doesn't work with HomeAssistant as I need to learn how to do the callbacks etc, but if it helps for me to use that module to dump the responses from my iZone just let me know what you need.

Thanks.

**Comment by lathiat** [comment]
Just wanted to chime in.. I have an iZone 310 installed Circa 2014.. this fix (tested by curling the discovery.py) works for me. Could you ship this release and update the component upstream as well? Thanks <3 

- Trent, Perth

**Comment by Swamp-Ig** [comment]
Ahh good to see that it works. I will patch it into the next release.

**Comment by bib555** [comment]
H

**Comment by Swamp-Ig** [comment]
OK this is successfully PRed in HA now. Should be out in next month's release.

**Comment by mikenye** [comment]
Hi @Swamp-Ig,

I'm still having issues with this.

When trying to add my iZone controller, I get the following:

```
2021-07-06 16:59:53 ERROR (MainThread) [pizone.discovery] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pizone/discovery.py", line 393, in initialize_controller
    await controller._initialize()  # pylint: disable=protected-access  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/pizone/controller.py", line 95, in _initialize
    str(self._system_settings['FanAuto'])]
KeyError: 'FanAuto'
```

**Comment by Swamp-Ig** [comment]
Can you take your fan out of auto mode and try again?

What do `http://izone_ip/SystemSettings` and `http://izone_ip/Zones1_4` output?

**Comment by mikenye** [comment]
Hi @Swamp-Ig,

Thanks for getting back to me.

My unit doesn't have an auto mode - the fan only supports high or low. It allows you to select medium, however after a couple of seconds it goes to high. There's no auto setting available.

Here's the output:

```
$ curl -v http://192.168.69.9/SystemSettings
*   Trying 192.168.69.9...
* Connected to 192.168.69.9 (192.168.69.9) port 80 (#0)
> GET /SystemSettings HTTP/1.1
> Host: 192.168.69.9
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Connection: close
< Content-Type: application/json
< Cache-Control: max-age=600
<
{
        "AirStreamDeviceUId":   "000000103",
        "DeviceType":   "ASH",
        "SysOn":        "off",
        "SysMode":      "heat",
        "SysFan":       "low",
        "SleepTimer":   0,
        "UnitType":     "Unknown",
        "Supply":       "0.0",
        "Setpoint":     "22.0",
        "Temp": "0.0",
        "RAS":  "master",
        "CtrlZone":     13,
        "Tag1": "",
        "Tag2": "",
        "Warnings":     "filter",
        "ACError":      "",
        "Id":   0,
        "EcoLock":      "true",
        "EcoMax":       "26.0",
        "EcoMin":       "18.0",
        "NoOfConst":    1,
        "NoOfZones":    7,
        "SysType":      "310",
        "AirflowLock":  "off",
        "UnitLocked":   "false"
* Closing connection 0
}
```

```
$ curl -v http://192.168.69.9/Zones1_4
*   Trying 192.168.69.9...
* Connected to 192.168.69.9 (192.168.69.9) port 80 (#0)
> GET /Zones1_4 HTTP/1.1
> Host: 192.168.69.9
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Connection: close
< Content-Type: application/json
< Cache-Control: max-age=600
<
[{
                "AirStreamDeviceUId":   "000000103",
                "Id":   0,
                "Index":        0,
                "Name": "Family",
                "Type": "const",
                "Mode": "open",
                "SetPoint":     23,
                "Temp": 0,
                "MaxAir":       100,
                "MinAir":       95,
                "Const":        0,
                "ConstA":       "false"
        }, {
                "AirStreamDeviceUId":   "000000103",
                "Id":   0,
                "Index":        1,
                "Name": "Front Lounge",
                "Type": "opcl",
                "Mode": "close",
                "SetPoint":     23,
                "Temp": 0,
                "MaxAir":       100,
                "MinAir":       5,
                "Const":        255,
                "ConstA":       "false"
        }, {
                "AirStreamDeviceUId":   "000000103",
                "Id":   0,
                "Index":        2,
                "Name": "Study",
                "Type": "opcl",
                "Mode": "close",
                "SetPoint":     23,
                "Temp": 0,
                "MaxAir":       90,
                "MinAir":       0,
                "Const":        255,
                "ConstA":       "false"
        }, {
                "AirStreamDeviceUId":   "000000103",
                "Id":   0,
                "Index":        3,
                "Name": "Master Bed",
                "Type": "opcl",
                "Mode": "open",
                "SetPoint":     23,
                "Temp": 0,
                "MaxAir":       35,
                "MinAir":       0,
                "Const":        255,
                "ConstA":       "false"
* Closing connection 0
        }]
```

**Comment by Swamp-Ig** [comment]
@mikenye 

> My unit doesn't have an auto mode - the fan only supports high or low. It allows you to select medium, however after a couple of seconds it goes to high. There's no auto setting available.

I can see the issue here. Opened a bug report in #11.

If you can update your code to match and test it locally that would be appreciated, post further comments on #11
